### ISSUE TITLE
npm audit를 하면 moderate vulnerability가 하나 나오네요.

### ISSUE THREAD

**Issue by Xen-alpha** [hsl0/libertygame-types#2]
![리버티게임 타입스크립트 통합 전 의존성 이슈](https://github.com/hsl0/libertygame-types/assets/5730311/5c9072b1-1c6b-42b8-958b-d7c0b4099165)
(이 사진은 npm install 하면 나옵니다)
dts-utils -> npm-registry-client -> request 순으로 생긴 의존성 트리에서  [request](https://www.npmjs.com/package/request) 지원 중단으로 인해 생긴 이슈로 보입니다.
심각한 문제는 아닌 것 같지만, 혹시 이 의존성을 다른 패키지를 사용하는 식으로 고칠 필요가 있을까요?

**Comment by hsl0** [comment]
dts-utils는 [definetelytyped](https://definitelytyped.org/)처럼 타입 선언만을 담는 패키지에 특화된 린터인 dtslint의 의존성입니다. [dtslint](https://www.npmjs.com/package/@definitelytyped/dtslint)는 모든 @types 패키지에서 사용하고 있습니다.

[dts-utils](/microsoft/DefinitelyTyped-tools) 레포지트리에서도 request 패키지를 사용하는 npm-registry-client 패키지 사용에 대한 문제 제기가 있습니다. microsoft/DefinitelyTyped-tools#543

이 패키지와 비슷하게 타입 선언만을 담지만 definetelytyped으로부터 독립적인 [mediawiki-types](https://www.npmjs.com/package/types-mediawiki) 패키지의 경우 기존에는 dtslint를 사용했지만, dtslint가 방치되었다는 문제가 제기되어 [tsd](https://www.npmjs.com/package/tsd)로 교체되었습니다. wikimedia-gadgets/types-mediawiki#25

**Comment by hsl0** [comment]
dtslint는 업데이트(#12)를 해도 맛이 간 것 같아서 제거하였습니다. (5ecceb1) tsd는 테스트 케이스가 필요해서 유닛 테스트를 도입할 때 도입하도록 하겠습니다.

**Comment by hsl0** [comment]
tsd를 테스트해보았으나, global 선언과 호환되지 않아 도입되지 못할 것 같습니다.

**Comment by Xen-alpha** [comment]
혹시 jest-typescript는 어떻습니까?

**Comment by hsl0** [comment]
jest는 런타임 코드를 테스트하는 것인데 여기는 런타임 코드 없이 타입만 담고 있기 때문에 실제 코드에 비해 테스트가 과해지지 않을까요? 이 레포지트리에서 필요한 테스트는 오직 타입 뿐입니다. 런타임 코드를 가져와도 안되고 필요해도 안돼요.

**Comment by hsl0** [comment]
tstyche를 테스트해보았는데 이거는 잘 되네요. 추후 테스트가 필요해지면 이걸로 쓰겠습니다.
